### ISSUE TITLE
Nit: Clboss ignores config options in c-lightning config if started with lightning-cli plugin start /path/to/clboss

### ISSUE THREAD

**Issue by devastgh** [ksedgwic/clboss#124]
Minor nit, as i seem to be uprading/compiling clboss a lot nowdays, i experienced if i want to stop and start the module while cln is running, that plugin start will ignore clboss options present in cln config file.
I don't know if this is the expected behaviour or not.
Thanks!

**Comment by ZmnSCPxj** [comment]
This is a C-Lightning bug --- it does not pass options from the command line/config file to the plugin if it is managed using `plugin start`.

**Comment by devastgh** [comment]
I see, thanks! I guess i'll open an issue there.

**Comment by ZmnSCPxj** [comment]
Problem is really how Core Lightning handles command-line options.  It splits handling into two stages, "early" and "late".  Plugin options like `--plugin` are handled during "early".  Then it loads plugins and gets their `getmanifest` so it knows what *other* command-line options are valid.  Then during the "late" stage it checks for plugin-provided options.  If an option is found which is not a built-in option or a plugin-provided option, and it was not processed during the early stage, it is flagged as an error.

Now, what happens if a plugin was not started as a `--plugin` and instead was done with a `lightning-cli plugin start`?  In that case, the plugin was never loaded during the "early" stage, and by the end of the "late" stage all the options must have been processed, and if there is an option which is neither built-in nor was provided by a plugin, then the option has to be raised as an error.

So if the plugin was started even later, after "late" option processing, then its options are ignored, since the original config file would have raised an error if it used an option that was provided by the plugin (and the plugin was not loaded beforehand).

Makes me wonder if switching everything to just `lightning-cli clboss-` commands and saving them to the database is better :(

**Comment by devastgh** [comment]
That would be the cleanest solution, probably. I guess it's a low priority issue though, at the moment.



> 
> Makes me wonder if switching everything to just `lightning-cli clboss-` commands and saving them to the database is better :(
