### ISSUE TITLE
Binary is 300MB. Am I doing something horribly wrong?

### ISSUE THREAD

**Issue by ProofOfKeags** [ksedgwic/clboss#138]
Chromium is that big, and I'd hazard a guess that this is doing far less.

also it looks like primarily dynamic linking still so it doesn't look like I mistakenly statically linked it.

**Comment by grubles** [comment]
```
$ du -sh /usr/local/bin/clboss 
270M    /usr/local/bin/clboss
```

Seems fairly large on my machine too.

**Comment by ZmnSCPxj** [comment]
No, but nearly all of it is in debug data:

```
zmnscpxj@developer:~/dvpt/clboss$ ls -lh clboss
-rwxrwxr-x 1 zmnscpxj zmnscpxj 276M Jun  9 09:19 clboss
zmnscpxj@developer:~/dvpt/clboss$ strip clboss  # removes debug data
zmnscpxj@developer:~/dvpt/clboss$ ls -lh clboss
-rwxrwxr-x 1 zmnscpxj zmnscpxj 10M Jul 11 20:06 clboss
zmnscpxj@developer:~/dvpt/clboss$ 
```

I am almost sure your Chromium binary has debug symbols stripped.

I can probably figure out something to remove debug symbols by default in the build.  Due to the `Ev::Io` framework, C stack backtraces are not accurate to the actual control flow; this is due to the `Ev::Io` framework being based on callbacks, where the C stack can be unrolled to the top main loop before a resumption point, and a suspension point might invoke an unrelated task using the same C stack (i.e. this is not a problem with `Ev::Io` per se, but rather an issue with the extensive use of callbacks).  Despite the loss of debuggability using stacktraces, `Ev::Io` does prevent a lot of callback-related bugs by construction, so I think it is still an overall win.

**Comment by ZmnSCPxj** [comment]
Setting `./configure CXXFLAGS="-O2"` removes most of the debug info (but `libsecp256k1` insists on including debug info).  The default of `autoconf` is to set this to `-g -O2`, where `-g` means "include debug info". Lemme figure out how to change the `autoconf` default....

**Comment by chrisguida** [comment]
Was hoping it would be something as simple as `strip` xD.

Thanks @ZmnSCPxj

**Comment by ProofOfKeags** [comment]
we could also just add a make target that includes the strip. It doesn't need to be the default.

**Comment by chrisguida** [comment]
All that's needed on the CLBOSS repo side, I think, is to document that `strip` is required to reduce binary size from ~300MB to ~10MB.

@ProofOfKeags: I assume you meant a make target here in the CLBOSS repo. Added to [Dockerfile](https://github.com/Start9Labs/c-lightning-wrapper/blob/fix/upstream-crashes/Dockerfile#L49) on our side unless/until the new make target exists.

**Comment by ProofOfKeags** [comment]
> @ProofOfKeags: I assume you meant a make target here in the CLBOSS repo. 

Yes. I'd imagine that no matter what it will be common enough to be useful to support directly from the CLBOSS build process. Whether it is the default to include or exclude debug info is something I don't feel the need to weigh in on. But I do believe having the ability to do dev vs production builds in the CLBOSS repo is a good idea, and would prevent leaking details to other build processes on precisely what the differences are. As @ZmnSCPxj stated, this could be accomplished with autoconf rules, which I believe is how the Makefiles are generated in the first place. However, it can also be accomplished without having any additional "smartness", where the autoconf ruleset unconditionally spits out a second make target that does the necessary stripping/optimization.

I'm not very familiar with how to use autoconf or the details of what it affords (not much of a C guy), but I was more just pointing out that I believe there is a low complexity solution to this.
