### ISSUE TITLE
Configuration - clboss-min-onchain

### ISSUE THREAD

**Issue by hosiawak** [ksedgwic/clboss#31]
Edited by ZmnSCPxj

Add a `--clboss-min-onchain` option that overrides our default 0.0003 minimum amount we leave onchain.

------

Original OP:

@ZmnSCPxj Are you planning to include some way to configure clboss (eg. by passing clboss-whatever options to lightningd.conf) ?

For example `clboss-max-channels = 30` meaning it'll try to open up to that many channels. Once it reaches this threshold it'll stop the opening process (even if there are onchain funds) but it'll continue its other chores (eg. rebalancing). The use case here is I'd like to have onchain funds in the wallet (eg. for swaps if it's an exchange) but not spend it all to open new channels. The default value could be 0 meaning the current behaviour.

**Comment by ZmnSCPxj** [comment]
I prefer to not have any configuration options at all, but I certainly understand that some use-cases may require them.

I was actually intending to have some way to set a minimum amount of onchain funds to leave.  If you notice, CLBOSS leaves a small amount of around 0.0003 BTC, which is intended to be used for anchor commitments and other onchain actions needed to maintain the node (currently not needed in Poon-Dryja, but may be needed later on when the network switches to Decker-Russell-Osuntokun).  This amount could be made configurable.

I think it is more useful to target an amount of funds to leave onchain rather than a specific number of channels, since CLBOSS can create channels as small as 0.005 BTC (absolute minimum size, though CLBOSS tries to create channels with 0.01 BTC at smallest if it can) to 0.15 BTC (just below the wumbo limit --- CLBOSS currently respects the wumbo limit), which would translate to fairly large deviations if the limit CLBOSS imposes is number of channels.

**Comment by hosiawak** [comment]
A minimum amount of onchain funds to leave would work too.

**Comment by ZmnSCPxj** [comment]
Okay, I will modify OP and subject to use minimum amount of onchain funds.
