### ISSUE TITLE
Support .onion fallback for Boltz-compatible swaps

### ISSUE THREAD

**Issue by ZmnSCPxj** [ksedgwic/clboss#45]
Recently, `boltz.exchange` had an expired SSL certificate which prevented CLBOSS from being able to reverse the polarity of our channels.

A possible workaround would have been to use the .onion, `boltzzzbnus4m7mta3cxmflnps4fp7dueu2tgurstbvrbt6xswzcocyd.onion/`, since this self-certifies.

What we could do would be to support using a "main" name and a fallback name, with the fallback name being an .onion.

**Comment by ghost** [comment]
Was wondering if there was (was going to be?) support for onion boltz exchanges and now I've set one up. Haven't figured out the dev-boltz api tool you mentioned to test if it is actually good to go, but I will and it appears to be.  
boltz api: jsyqqszgfrya6nj7nhi4hu4tdpuvfursl7dyxeiukzit5mvckqbzxpad.onion    
lnd node underneath: 0231a280b05728e89e77589ce93a38ff92a7a7b7e7c5e05aab6b7bda577b6640b0@dl3rgjtcamvffksdcqhr7j6u5spu7tmzbxbn4ojww2lorliu2u2w7syd.onion:9735  
  
Was also thinking that if you already have a list of boltz exchanges, why extend to have a fallback rather than just include more in the list?

**Comment by ZmnSCPxj** [comment]
The boltz.exchange site has a hidden service as well as a DNS public network name, that is what I am referring to here.

We should not add the boltz.exchange hidden service as a separate Boltz-API exchange *and* the public DNS name, we need to give them as alternate names to a single service somehow.  Note in particular that we store information in the db and use the name as the key in the db, so  if the public DNS site is down we should try the .onion to the same service, they are just alternate names for the same thing.

In particular if you already have a swap ongoing with boltz.exchange and *then* their public DNS site goes down you really want to be able to fall back, knowing it is the *same* exchange but using Tor instead.  Onchain activity is slow enough that the CLBOSS and its LN could get intermittently shut down in the meantime, and then the DNS cache is cleared and then you have a DNS problem and now you cannot talk to the site, that sort of thing, so if the site supports alternate ways of accessing them, you want a fallback, not *just* alternate swaps.

If you are unaffiliated with the boltz.exchange site I can easily add your .onion site.  How committed are you to running this permanently?

**Comment by ZmnSCPxj** [comment]
The `dev-boltz` does not use proxy BTW but you can try it with `torify`.

**Comment by ZmnSCPxj** [comment]
@AutonomousOrganization got this error while trying to get invoice:

```
ERRROR Boltz::Service("http://jsyqqszgfrya6nj7nhi4hu4tdpuvfursl7dyxeiukzit5mvckqbzxpad.onion"): Unexpected result from service: {
        "error" : "unknown service invoicesrpc.Invoices"
}
```

This seems to have occurred while doing `/createswap` to your Boltz API, could you check?  Maybe some permissions problem with the `lnd` node?

**Comment by ZmnSCPxj** [comment]
Here is `diff` to make `dev-boltz` talk to your site, also, need to invoke in `torify`.  `./dev-boltz get-quotation $satoshis` works fine, it is `swap` which fails.

```diff
diff --git a/dev-boltz.cpp b/dev-boltz.cpp
index 116f707..ee6e177 100644
--- a/dev-boltz.cpp
+++ b/dev-boltz.cpp
@@ -159,7 +159,7 @@ int main(int argc, char** c_argv) {
        auto code = Ev::lift().then([&]() {
 
                /* Create service.  */
-               return factory.create_service("https://boltz.exchange/api");
+               return factory.create_service("http://jsyqqszgfrya6nj7nhi4hu4tdpuvfursl7dyxeiukzit5mvckqbzxpad.onion");
        }).then([&](std::unique_ptr<Boltz::Service> n_service) {
                service = std::move(n_service);
```

**Comment by ghost** [comment]
Did see the logs of your attempts +1. lnd needs to be compiled with tag invoicesrpc, which I saw in the docs. Think may have just put 'tag=' instead of 'tags=' in that compile, so I've fixed that. I've no affiliation to boltz and have every intention to leave this running permanently both to help the network and to drive some useful routing through my nodes. Looks like I've got another error on a swap attempt, ~~will let you know if I get this working.~~ looks like it's working but won't swap right now due to chain fees

**Comment by ZmnSCPxj** [comment]
> looks like it's working but won't swap right now due to chain fees

Haha yes, there is indeed a check to limit the fees, better to check when onchain fees are low.
