### ISSUE TITLE
ChannelCandidateInvestigator - how does it work ?

### ISSUE THREAD

**Issue by hosiawak** [ksedgwic/clboss#46]
Looking in the logs I noticed this:

```
plugin-clboss: ChannelCandidateInvestigator: Best candidates: 02df9bc4315c733658aaa910e7a857b0c34a1541dfb31bdffdd5eefa08c9da0f26
(24), 03afdfd5020decc582a9aedfc5190403117ec83cc0e5993a1e5bfb8448b7c5ee59(24), 029da80a069c1e6e854e127c022d4d6a725b3a8a5e7feb297e9ae1f336a2b74a8e(24), 03505902c83
ba1971c44e15736db0843271ec50a7741d0b15122f9e0d6d8a7ca98(24) ...
```

The first few nodes have 1 or 2 channels with very little capacity. I think it'll try to open a channel to `02df9bc4315c733658aaa910e7a857b0c34a1541dfb31bdffdd5eefa08c9da0f26` when fees drop but what's the reasoning behind it ?

How does the ChannelCandidateInvestigator work ? What determines if it's a good candidate ?

**Comment by ZmnSCPxj** [comment]
The candidates are chosen by `ChannelFinder` algorithms:

* `ChannelFinderByPopularity` - looks for nodes with high number of peers, and selects one of the peers of popular nodes (not the popular nodes directly, but the popular ones tend to also be the peers of each other).
* `ChannelFinderByDistance` - runs a Dijkstra from your node, and selects nodes that are distant from you (i.e. high fees coming from you).
* `ChannelFinderByListpays` - looks at your payments, and selects nodes according to the number of payments you made to that node.
* `ChannelFinderByEarnedFee` - looks at your peers and how much their `out_fee_msat_per_day` is, and selects a peer of high-earnings peer.

Candidates are actually pairs of nodes: the `proposal`, which is the actual node to be channeled with, and the `patron`, a node which we think is a good reason why we should connect to the `proposal`.

Here is how the above algorithms indicate as `patron`:

* `ChannelFinderByPopularity` - the popular node is the `patron`.
* `ChannelFinderByDistance` - the Dijkstra algo generates a shortest-path tree.  The `patron` of a distant node is its parent (a peer of that node that is one step closer to us than the leaf) in the shortest-path tree.
* `ChannelFinderByListpays` - no `patron` --- it passes candidates through `ChannelCandidateMatchmaker`, which selects an existing candidate, gets the shortest path between the new candidate and the old candidate, and selects the first hop from the new candidate as the `patron`.
* `ChannelFinderByEarnedFee` - our peer that had high earnings is the `patron`.

The `patron` is important because that is how we estimate the flow of the candidate.  It is not shown in most of the `ChannelCandidateInvestigator` logs, or in the `clboss-status` output, but it would probably be a good idea to do so.  The `patron` is stored in the database along with the `proposal` (i.e. the actual candidate).

After that, they go through `ChannelPreinvestigator`, which does two things:

* check if it is up *right now*.
* check if it has capacity, by using the `Dowser`.  The `Dowser` estimate must be at least 5mBTC.

The `Dowser` estimates the capacity of the `proposal` towards the `patron`.  This is done by doing a few `getroute`s from the `proposal` to the `patron`, finding the smallest channel along the path, then taking its capacity and dividing it by the route length + 1.  It only takes into account short routes of 1 or 2 hops, and sums up all the estimated per-route capacities.

You can access the `Dowser` algorithm via `clboss-dowser`.  First arg is the `proposal`, second is the `patron`.

Then, they enter `ChannelCandidateInvestigator`, which only really checks their uptime (i.e. we can `connect` to them).

Later, when the `ChannelCreationDecider` decides that creating some channels would be nice, this will trigger the `ChannelCreator`, in particular the `ChannelCreator::Planner`.  The planner takes the list of candidates from `ChannelCandidateInvestigator`, and runs the `Dowser` over the top candidates to determine their flow.  In particular, it checks if the `Dowser` result is at least 5mBTC, and if the `Dowser` results in less than that, will reject the node from channeling.  It then uses the `Dowser` result to tell it how much to put in a channel to a candidate.

Looking at your log, `02df9bc4315c733658aaa910e7a857b0c34a1541dfb31bdffdd5eefa08c9da0f26` is indeed a low-capacity node, but it is connected to `rompert`, which is fairly popular, so it might have been `ChannelFinderByPopularity`.  The `ChannelFinderByDistance` also tends to select low-capacity nodes, since distant nodes tend to be low-capacity.

(It would probably have been a good idea to record the algorithm that proposed a node for channeling lol).

On the other hand, we can observe that `patron`s are always peers of the `proposal`.  So if `rompert` (`02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b`) is the patron of the proposed node, we can ask the `Dowser` about its estimate, which on my system is:

```
$ lightning-cli clboss-dowser 02df9bc4315c733658aaa910e7a857b0c34a1541dfb31bdffdd5eefa08c9da0f26 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b
{
   "amount": "49250000msat"
}
```

That is below the 0.005BTC limit, meaning the `ChannelCreator::Planner` will reject the node if `ChannelCreationDecider` decides to create channels now.  Looking at 1ml, the `02df9bc4315c733658aaa910e7a857b0c34a1541dfb31bdffdd5eefa08c9da0f26` proposal seems to have had some small 0.001 channels in the past, which are closed now; at the initial preinvestigation it probably had just enough capacity to squeeze past the 0.005BTC minimum.

`ChannelCandidateInvestigator` does not check `Dowser` flow, since there is the possibility of a channel shock where a node closes most of its channels, but then re-establishes them later, so I did not want to eliminate candidates *just* due to low flow until just before the `ChannelCreator::Planner` gets to them.  `ChannelCandidateInvestigator` is strictly about uptime, since investigating uptime is really what is time-consuming --- estimating flow is something you can do just before actually making a channel, and is more relevant during actual channel creation.

(on the other hand, users of `clboss` might worry, so maybe I can just drop low-flow candidates at `ChannelCandidateInvestigator`; I do not expect channel shocks to be *common*, but who knows? It happened in the past...)

In any case, even if we end up making a channel to it --- for example if it makes a few more small channels in the vicinity of rompert --- then `Dowser` will still give it a fairly low flow of about 0.005BTC, so `clboss` will make a channel to it that is only about 0.005BTC, which is a reasonable risk, as it has a 0.01 channel with popular node `rompert`.  For all we know, the `proposal` might  be underserved by the rest of the network and it would appreciate the capacity (which is why `ChannelFinderByDistance` exists).

**Comment by hosiawak** [comment]
@ZmnSCPxj Thanks for the detailed description, it makes more sense now. I guess it would be valuable to turn the above into a document, either appended to the README or created inside a docs folder for the noobs like me. I can work on it if you think it's useful?

**Comment by ZmnSCPxj** [comment]
Sure, I suggest putting in a new `docs/` directory, and link from the `README.md`.

**Comment by ZmnSCPxj** [comment]
There is probably a lot more I need to explicate in its algorithms as well.  Most of my notes are scattered in various comments in lots of scattered modules.  I suppose that is the weakness of the overall bus-based architecture --- algorithms involve the behavior of lots of small modules, and you have to kinda be able to imagine the interactions between the many small modules.

**Comment by hosiawak** [comment]
@ZmnSCPxj - are you available on IRC or something like that? I have some questions wrt fees and don't want to spam you with issues on GH.

**Comment by ZmnSCPxj** [comment]
Sorry, had to do some reinstalls, will set up IRC again.

**Comment by ZmnSCPxj** [comment]
See also: https://zmnscpxj.github.io/clboss/03-investigation.html
