### ISSUE TITLE
Possible to run on testnet?

### ISSUE THREAD

**Issue by grmkris** [ksedgwic/clboss#48]
Locking 0.01 bitcoin to properly test this software is quite a lot for me and I am debating whether to use this software or not. 
Whoever if it would be possible to deploy this on testnet first I'd be much more comfortable deploying it on mainnet after some time...  

I think the idea for this project is great and I am prepared to do the necessary changes to use this on testnet. I'd just need some pointers / instructions. 

Thanks

**Comment by ZmnSCPxj** [comment]
In theory it "can" run on testnet, but at much reduced functionality:

* Normally CLBOSS will connect to nodes on the existing network.  I have ways to do that for mainnet but not for testnet.
  * `ConnectFinderByHardcode` needs some reliably high-uptime nodes for mainnet, but not for testnet.  I need to locate some high-uptime nodes for testnet (if you have a good curated list, that would be appreciated).  The issue here is that since testnet coins are valueless, people are not really incentivized to keep their nodes high uptime --- they may run their nodes at high uptime for a few weeks, then shut them down completely, so the list needs to be continuously maintained and filtered by somebody to ensure it does not rot.  The hardcoded list for mainnet is a lot less maintenance-heavy since people who have high-uptime mainnet nodes *now* have an incentive to *keep* them high-uptime in the future.
  * `ConnectFinderByDns` has DNS servers for mainnet but not for testnet.  I do not know if anyone runs a DNS server for testnet nodes.  In any case, it also runs into the same issue as above --- people tend to not keep their testnet nodes up, so a testnet DNS server might give long-dead testnet nodes when you query it for a list.


Other than the above, I think CLBOSS "should" work on Bitcoin Testnet.  So for now, you have to manually maintain connections to the testnet network to download the gossip map.

**Comment by sangaman** [comment]
When I try running this on testnet, it gets stuck on:

```
2021-12-07T15:26:36.578Z INFO    plugin-clboss: ChannelFinderByPopularity: Not enough nodes with >0 channels in routemap (only 309, need 800), will try again later.
```

I'm guessing the public testnet LN is currently only around 309 nodes, and therefore clboss never finds enough nodes and never does anything. It also doesn't seem that there's anyway to configure this 800 node limit, so I'm stuck. It seems like a key feature to be able to give this a test drive with testnet funds before committing mainnet funds.

As a side note, I'm guessing swapping off-chain/on-chain funds and purchasing inbound liquidity via boltz.exchange won't work in testnet?

**Comment by ZmnSCPxj** [comment]
boltz.exchange has a testnet swapper, actually.  https://testnet.boltz.exchange/api It is already coded into CLBOSS, though untested, obviously.

Lemme see about that 800-limit... There used to be ~1000 testnet nodes in the past I think. Guess everyone is #reckless now....

**Comment by sangaman** [comment]
Making the node count minimum configurable would be good I think. I could even imagine wanting to make this limit much smaller for private regtest networks or something. I actually looked at the code to see if it would be something I could implement myself but my C++ is very rusty and it wasn't immediately clear to me. Thank you!

**Comment by theborakompanioni** [comment]
> Making the node count minimum configurable would be good I think. I could even imagine wanting to make this limit much smaller for private regtest networks or something.

Interested in this too. Would love to be able to investigate and test this on regtest. What is the chance that this will be considered?
Thank you for this very promising piece of software :pray:

**Comment by ksedgwic** [comment]
I've been using CLBOSS in testnet for a bit. I needed these modifications: https://github.com/ZmnSCPxj/clboss/pull/156

**Comment by ksedgwic** [comment]
Closing because CLBOSS runs on testnet currently
