### ISSUE TITLE
Delayed clightning startup when offline

### ISSUE THREAD

**Issue by erikarvstedt** [ksedgwic/clboss#49]
When run on a system without WAN access, `clboss` adds about 18 seconds to service startup time (defined as the duration from starting the clightning process to the start of the RPC server). This delay is due to failed DNS resolution.

[clightning service output (gist)](https://gist.githubusercontent.com/erikarvstedt/2db1a591f1bc2b1ef0d92d59ea22f2dd/raw/7f6a6c1024ac6ecfc06d9ecc0c60ea67ebeda67d/clboss.txt)

#### clightning config file
```
network=bitcoin
bitcoin-datadir=/var/lib/bitcoind
proxy=127.0.0.1:9050
always-use-proxy=true
bind-addr=127.0.0.1:9735
bitcoin-rpcconnect=127.0.0.1
bitcoin-rpcport=8332
bitcoin-rpcuser=public
rpc-file-mode=0660
plugin=/nix/store/zd4y7s4vi43sjvmvyp6sv4zhc31rkk9l-clboss-0.10/bin/clboss
clboss-min-onchain=30000

disable-dns
bitcoin-rpcpassword=1s36RENe8gF7cYD8Zlm9
```

When `dig` is not in `PATH`, there is no delay: [clightning service output  (gist)](https://gist.githubusercontent.com/erikarvstedt/387f467bebb158126356c3dd89009795/raw/be830b68df38a5025affa132f8b80c189ea7a7b3/clboss-no-dig.txt).

This issue appeared when I added `clboss` to our [nix-bitcoin](https://github.com/fort-nix/nix-bitcoin) test suite, which runs bitcoin nodes including clightning in offline VMs.\
It would be great if `clboss` could handle missing WAN at startup without delaying the main clightning process.

**Comment by ZmnSCPxj** [comment]
Hmm.  Assuming the log timings are correct, it seems CLBOSS is getting a delay in manifestation (because even the `lightningd` initialization is delayed!), which would happen only if `DnsSeed::can_get()` is slow.  On my system, `DnsSeed::can_get()` is fast even if WAN is down.  `DnsSeed::can_get()` uses `dig localhost` to check if `dig` is installed, and that is fast on my system even if WAN is down.

`DnsSeed::can_get()` is one of the few things we call before we enter the mainloop, and manifest handling is done in the mainloop, so that might be the issue.

Let us try if a quick fix to change it to `dig -v` would work.

**Comment by erikarvstedt** [comment]
Thanks, `dig localhost` is indeed the cause:
```bash
$ time dig localhost
; <<>> DiG 9.14.12 <<>> localhost
;; global options: +cmd
;; connection timed out; no servers could be reached
real	0m18.026s
user	0m0.005s
sys	0m0.005s
```
