### ISSUE TITLE
Fee Modder by Expenditures

### ISSUE THREAD

**Issue by ZmnSCPxj** [ksedgwic/clboss#56]
We keep track of `FundsMover` expenditures anyway, but only use it to limit `JitRebalancer` to prevent targeted attacks if the attacker knows we use JIT rebalancing.  An idea from @hosiawak : https://github.com/ZmnSCPxj/clboss/pull/55#issuecomment-753238276

Here is a possible implementation:

* Compute `out_expenditures` divided by `out_earnings` for each channel as a `double`.  If this data is nonexistent, or `out_earnings` is zero, saturate to some maximum (maybe 100.0?).
*  Give that ratio as the multiplier returned by this `FeeModder`

For reference, the `FeeModder` system allows modules to provide a `double` that is multiplied to a computed basis fee.  This computed basis fee is the median of fees that other channels to that node have.

While this may be workable, we should note that if CLBOSS uptake is high, then since the basis we use is the fee that other channels charge, if the other nodes are also using CLBOSS this can lead to absurd situations where CLBOSS-managed nodes start bumping up channel feerates, then their competitors see the median as going higher and also bump up their channel feerates, etc.  Or similar absurd situations in the reverse direction.  So I'm wondering if the median-fee should instead be used as an initial fee when we have no information yet and to use #11 of some kind to change this initial feerate over time as we try to discover the optimum price based on our position in the network.

**Comment by hosiawak** [comment]
Here's out_expenditures / out_earnings from my sample:

<pre>
mod|base msat|feerate %
107.88|19938|0.002
35.35|3539|0.0035
535.9|1108|0.0001
</pre>

How will the new Modder affect each base fee and fee rate in this example ?

Why do you omit in_earnings/expenditures - what do these mean ?

**Comment by hosiawak** [comment]
_While this may be workable, we should note that if CLBOSS uptake is high, then since the basis we use is the fee that other channels charge, if the other nodes are also using CLBOSS this can lead to absurd situations where CLBOSS-managed nodes start bumping up channel feerates, then their competitors see the median as going higher and also bump up their channel feerates, etc._

I think this will be true even without high CLBOSS uptake for any routing node which has operational costs (rebalancing fees being one kind of them) tied to the general fees on the network. When I think about a routing node where:

a. it earns fees by forwarding sats and the fees are proportional to the capital forwarded and it's a competitive fee market (your node routes only if using competitive fees)
b. it has to pay for rebalancing its channels which is also proportional to the capital forwarded using similar feerates on the network (competitive fee market)

then I don't see how it can stay profitable in the long assuming the fees it earns (a.) don't differ much from the fees it has to pay for rebalancing (b) (which is the common case today).

One way around it would be to introduce imbalane eg. by using "our own" subnetwork of nodes, with private channels and zero fees that are setup in such a way that they can to rebalance all our routing nodes and each other. I don't even know if this is possible. Even if this was possible running such a subnetwork of nodes would still incur some costs.

Maybe I'm missing something obvious here but if you have any thoughts on this I'd love to discuss them.

**Comment by ZmnSCPxj** [comment]
In a way, one can consider the "business" of forwarding nodes to ***not*** be to provide liquidity, but instead, to ***aggregate payments***.

Consider, that each actual non-rebalancing payment must match a particular fixed amount that is demanded on the payee side.  For bookkeeping purposes, the payee must have individual payments from each payer, so that it knows which payer has paid for which value.

However, ultimately the actual value in each channel is an aggregate of multiple payments.

Thus, perhaps a way out here is to consider that:

* Multiple people will pay to some payee via the shortest path (they are seeking to reduce fees they pay).
* When the capacity on the shortest-path channel is low, the forwarding node can move funds along a "longer" roundabout path, to re-load the shortest-path channel.
* Thus, "true" users of the network will make multiple small payments along the shortest path, then the forwarding node makes a few large rebalances that are less efficient in path, but which it can afford to do since it is earning money from the small payments.

This suggests to me that what we should really do is bump up the `base` fee by quite a bit and lower the `proportional` fee.  This gives an asymmetry between the "real users" who are many and who have to pay many small payments to the payees, vs. the forwarding node who gets to aggregate multiple payments and facilitate payment between payers and payees.

**Comment by ZmnSCPxj** [comment]
Closed, as by-price-theory already works for this, and is arguably better.
