### ISSUE TITLE
InitialRebalancer behaviour

### ISSUE THREAD

**Issue by hosiawak** [ksedgwic/clboss#67]
@ZmnSCPxj I noticed that InitialRebalancer will exclude channels from rebalancing once we hit 0.1% in expenditures 

https://github.com/ZmnSCPxj/clboss/blob/ddb61672419f5fb2dc4d5e5923ca122729077275/Boss/Mod/InitialRebalancer.cpp#L310

I think this line should at least take into account earnings because now I have a bunch of unbalanced channels that will not be rebalanced because their capital flow is unidirectional pretty much. 

Even if we take earnings into account it will hit this threshold though because right now the earnings are an order of magnitude lower than the expenditures.

After looking at this for the past few weeks I concluded that the whole fee estimation system in clboss should eventually be based on how much we spend on maintaining channel balance because that's the main cost for running a routing node.

I have a large channel with the biggest merchant on LN. Initially I had all the capital on my side of the channel but CLBOSS managed to balance this channel using its brilliant rebalancing logic (something I couldn't do manually with the `rebalance` or the `drain` plugins). This was due to the fact that clboss learned from erring_node messages and with each rebalancing route got smarter and smarter. This part of CLBOSS:

* is just *awesome* 
* saves a ton of manual work
* puts your node on the [BOS list](https://nodes.lightning.computer/availability/v1/btc.json) (the top 5% of all the LN nodes) automatically

Then all this balanced liquidity got sucked up by capital flowing from the merchant node, via my node, to a couple other big nodes to which I have a large channel with outbound liquidity. This happened in a matter of 2 hours and now I'm back at square one with an unbalanced channel to the biggest merchant and a lot more spent on rebalancing this channel than I earned by forwarding to the other nodes.

What should have happened IMHO?

CLBOSS should recognize that it spent X on rebalancing the big merchant channel but the fees it earned by forwarding this capital out to the other nodes did not make up for it. 
 
Let's assume we have a channel with a merchant M1, and 2 routing nodes N1 and N2.

Inital rebalancing 8 million sats for M1 cost: 13k sats
M1 state: 8 million sats inbound and 8 million sats outbound
Our fee rate to N1: 0.001%
Our fee base to N1: 1000 msat
Our fee rate to N2: 0.005%
Our fee base to N2: 5000 msat

Then M1 forwards 4 million sats (presumabely because it cares only about incoming liquidity) via us and N1 and 4 million via us and N2 in 20 transactions for each node:

N1: 40 * 1 sat + 0.001% * 4000000 sat = 80 sats
N2: 40 * 5 sat + 0.005% * 4000000 sat = 400 sats

We earned a total of 480 sats but we spent 13k on rebalancing.

This is the fundamental problem with the current CLBOSS fee setting system as I see it right now. It can start with a competitive low fee (FeeModderBySize is fine for starters) but then it needs to take all these 13k spent on rebalancing across all channels and update all outgoing fee rates (because fee rates reflect the cost of maintaing capital balance) using a weighted median or sth like that so that the rebalancing cost is reflected in our fees. Manipulating base fee can be done separately using different factors but I don't believe manipulating base fee will solve the above problem in the long run.

All the above observations apply *only* to routing nodes. Merchant nodes and user nodes should behave differently (merchant mode focusing on maintaining incoming liquidity and user mode on maintaining small, balanced set of channels to well connected nodes - but this is a whole new subject).

**Comment by hosiawak** [comment]
<pre>
FundsMover: Moved 569321323msat from X, getting 569309006msat to Y, costing us 12317msat.
FundsMover: Moved 1866929629msat from A, getting 1866773553msat to B, costing us 156076msat.
FundsMover: Moved 1845652369msat from C, getting 1843614038msat to D, costing us 2038331msat.
FundsMover: Moved 2182428110msat from X, getting 2173234426msat to Z, costing us 9193684msat.
</pre>

<pre>
Total moved: 6452931023
Total cost: 11400408
Minimum fee rate that covers these costs = 11400408 / 6452931023 = 0.1766%
</pre>

None of the fee setting strategies present in any of the current PRs result in such fee rate, it's usually an order or 2 or 3 magnitudes lower.

**Comment by hosiawak** [comment]
I guess I'm missing the fact that this is an "initial" rebalancer so designed to kick in at the start and then stopping.

So the next question then is what's supposed to kick in and balance these unidirectional channels again, anything ?

**Comment by hosiawak** [comment]
It's me again with some observations, I don't have detailed stats or graphs this time just a tl;dr. Please bear in mind that these are my personal observations that may not apply to your node but I feel the need to share them regardless of whether or not they find their way into CLBOSS codebase:

1. Personaly I'd merge #61 - good direction in general

2. Don't merge #59 or #62 because these changes result in what I'd call "cosmetic" fee updates. They don't change the fee structure in any fundamental way but only add complexity to the codebase. 

3. Add a config option to turn off all automatic fee setting in CLBOSS and allow manual fee strategies. Basically disable [these modules](https://github.com/ZmnSCPxj/clboss/blob/master/Boss/Mod/all.cpp#L159-L164) by setting a config option. This will allow me to still use CLBOSS but experiment with manual fee strategies - at least until CLBOSS is better at estimating fees than my manual setting. Right now manual fees yield better returns than automatic.

4. Add config options (with good defaults) to specify min/max-fee-rate and min/max-fee-base. My preferred defaults:
    -min-fee-rate=0
    -max-fee-rate=5000
    -min-fee-base=0
    -max-fee-base=50000

5. Add a config option -fee-num-ranges that splits the ranges above in the that many possible discrete values, eg (using the defaults above and -fee-num-ranges=11):
possible-fee-rates=[0,500,1000,1500,2000,2500,3000,3500,4000,4500,5000]
possible-fee-bases=[0,5000,10000,15000,20000,25000,30000,35000,40000,45000,50000]
Then all the fees need to fall into the ranges above. For example instead of using 331 fee rate use the closest upper fee rate which in this case would be 500. The main motivation behind this would be to minimize fee update announcements if they're not substantial (eg. going from 331 to 358 fee rate) and make it easier to understand to node operators what's going on. I think this could be implemented as a final fee modifier that places the estimated fees in these bins. For now (until the automatic CLBOSS estimation becomes better) I'd give the user the option to decide what the allowed ranges should be to leave room for experimentation.

6. Make the module that manipulates fees to achieve a balanced channel (I don't know its name and I haven't checked) - the one that lowers fees when most of the balance is on our side and increases fees when most of the balance is on the remote side - more aggressive. Especially more agressive in terms of setting zero fees to quickly rebalance the channel for free.

I find 3. the most important because it'll allow me to experiment with manual fee strategies and then 4 and 5 because that's what's I'm doing manually. I wish I could send a PR for these but I don't think my C++ skills are there yet (working on it).

What I'm evaluating right now:

1. Setting the fee rate ~ 2500 (0.25%) and fee base ~ 500 (default for most channels)
2. Unbalanced channels with most capital on our side - fee rate and fee base = 0 until they become somewhat more balanced then back to 1.
3. Balanced channels with large traffic - experiment with raising fee rate up to 5000 or 7500 to cover the rebalancing cost.

I think rebalancing and fee estimations are huge research areas and we haven't even scratched the surface. Personally I'll continue my small experiments and report back if I observe anything that might be useful. Thanks.

**Comment by ZmnSCPxj** [comment]
> I guess I'm missing the fact that this is an "initial" rebalancer so designed to kick in at the start and then stopping.
>
> So the next question then is what's supposed to kick in and balance these unidirectional channels again, anything ?

`https://github.com/ZmnSCPxj/clboss/blob/a2c57272c01410ceb23414b8609cea31327b6239/Boss/Mod/EarningsRebalancer.hpp#L10-L14

Unfortunately I have not gotten it to trigger at all, since earnings are tiny compared to expenditures.

> fee estimations are huge research areas 

Indeed.  I implemented a `FeeModderByPriceTheory` which does this research for you.

Below are my notes: https://github.com/ZmnSCPxj/clboss/blob/a2c57272c01410ceb23414b8609cea31327b6239/Boss/Mod/FeeModderByPriceTheory.cpp#L27-L49

-----

Here is a sketch for an algorithm.

First, let us define a `std::int64_t`, called `price`, for each channel.
Let us consider that it generates a multiplier: if `price` is negative, the multiplier is 0.8 ^ -`price`, if it is positive the multiplier is 1.2 ^ `price`.

Initially, each channel starts with a `price` of 0.
The algorithm operates on a per-channel (per-peer?) basis.

At the start, the algorithm shuffles a small deck of cards with `price - 2`, `price - 1`, `price`, `price + 1`, and `price + 2` and initializes the deck with those cards.

It draws the topmost card in the deck, then sets the multiplier by the `price` marked on the card.
While the current card is in play, it records every forwarding fee it successfully receives on the card.
Once it has some number of days (2-3 days?) of data, it discards the card and draws a new one.

If the deck is empty when the algorithm wants to draw a card, it looks at the discard pile and selects the card with the highest total earned forwarding fee.
It then sets the `price` to that card, then destroys the discard pile and creates and shuffles a new deck of cards using the new `price`.

* The above algorithm naturally walks around some current `price` level that is assumed to be optimal, but seeks out nearby alternatives that may be better.
* We assume that there are no local optima; price theory suggests that local optima should not exist, rather, there is some single globally-optimum price that delivers the most amount of goods at the most economic cost.
  * Thus, we do not need to perform random large steps in order to escape local optima.
* The algorithm "forgets" old data so it can adapt to changes in LN connectivity and changes in economic conditions.
* Shuffling the deck is necessary to prevent locking onto some regular periodic phenomenon on the network.
  The shuffling ensures any regular periodic phenomenon that matches our sampling period (or multiple thereof) will randomly select one of he possibilities uniformly at random.

**Comment by hosiawak** [comment]
Thank you @ZmnSCPxj - Investigating how the FeeModderByPriceTheory works now.
