### ISSUE TITLE
Discover channel candidates by earned fee

### ISSUE THREAD

**Issue by ZmnSCPxj** [ksedgwic/clboss#7]
As an automated node manager, we want CLBOSS to discover for itself what Lightning nodes are popular payment targets, so that we can build channels to them.

Now, we could implement a general AI that can understand Bitcoin news outlets to find hyped services and figure out which Lightning nodes are connected to those and so on, but that would require a lot of effort.

However, from the position of our node in the network, we do get to gather some amount of information.  In particular, we can determine which of our current peers has been earning us more fees (i.e. which ones have the highest payments going to them).

This suggests that the peer itself, or the peers of that peer, are popular destinations on the network.  So increasing our capacity towards that peer (and its other peers) might be a good idea.

Effectively, we theorize that if one of our peers has a lot of payments going to it, then one of *its* peers is probably the destination.  We can try to guess which peer of our popular peer is the target.

* If we guess wrong (likely) it is at minimum an easy source of channel rebalancing.
* If we guess right, then we have undercut our peer and get a direct channel to the actual popular node.

Thus, we want to implement some kind of heuristic to propose channels to nodes that are peers of our own peer that has many outgoing payments going to it.

**Comment by Saibato** [comment]
> Now, we could implement a general AI that can understand Bitcoin news outlets to find hyped services and figure out which Lightning nodes are connected to those and so on, but that would require a lot of effort.

That;s way easier than one thinks, the magic is don;t over eng that, make it as simple as possible, stop think in words ( languages are just a locally abstraction ) think in pictures and assign them PDE's or cyclic groups of pattern involvement that u can easy filter with a mixer like a radio u tune in the *meaning* and accept that 90% is a good guess, perfection is a speed killer and impossible ( Goedel ), fault tolerant is key to success to match a PDE or cyclic metric u choose, it matters anyway not in the subreality, but in real world its useful , btw vision works that way , since I am about to write tools able to attack AI where ever it finds it, that does not mean i will use them, i am pro AI and wait for it to come in my boring world, so please build this.

So since I guess, the google patent of 1998 runs out i used to gain all the info I needed about this world, it should be quite simple to adapt the idea and write a crawler that could exactly do this, as long as AI does not go BIO we won;t face serious resistance.

And remember if they figure out what bitcoin did and see the inevitable, they will be serious foes, as specially if they figure out how we used there greed and covert information gathering to gain patents and establish leverage and the pig system against them, they will get for sure in rage like mad. So we will need constrains.
