### ISSUE TITLE
ChannelCandidatesPreinvestigator to drop Candidates which have too small capacity to their Patron

### ISSUE THREAD

**Issue by hoplaaa** [ksedgwic/clboss#85]
Following #81 

ChannelCandidatesPreinvestigator do not consider Candidates capacity to their Patron.
As a result, 2/3 of the candidates are useless. They are monitored kept as good candidate until a `ChannelCreator` is called.
ChannelCreator rejected them during channel creation process : 
https://github.com/ZmnSCPxj/clboss/blob/00cdded89cd5eac01ee5c6bb4675ecc7fa20778f/Boss/Mod/ChannelCreator/Planner.cpp#L81-L85

It would be better to directly drop wrong candidates: better visibility, no useless active monitoring, slots not taken by fake candidates, ...

**Comment by ZmnSCPxj** [comment]
Rather than drop canddates at the `ChanneCandidatePreinvestigator`, I think we should split it at two levels:

* Some `ChannelFinder`s do not locate a patron  (e.g. `ByListpays`).   These locate a patron by asking help from `ChannelCandidateMatchmaker` to look for a patron.  The matchmaker could consider channel size --- the matchmaker really just does a `getroute` from the candidate to an existing candidate (on the logic that existing candidates are good, so connectivity towards those candidates is also good) and takes as patron the first hop; rather than route a 1msat paymant (current behavior) it could route a 5mBTC payment, which should immediately rule out small channels to the patron on recent C-Lightning.
* Channel topologies can change from under us, so `ChannelCandidateInvestigator` should be the one to filter out candidate-patron pairs whose channel capacities have dropped below the minimum.  Keep `Preinvestigator` simple and make it a quick check, and add a `Janitor` sub-object to `ChannelCandidateInvestigator` that invokes the dowser and cleans up the candidate list.  This handles not only the low-capacity candidates in the start but also handles channel topology changes, which we do not control.

**Comment by hoplaaa** [comment]
Nice, I like the Idea of the `Janitor` doing the maintenance of the candidate list.
